### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by emht** [championshuttler/MAA-Avaya-Hackathon#1]
Please Provide a readme.md.  I couldn't understand what the project is about.  It's always better to have a good user-friendly readme.md available for others to understand your project.

Because Coding is not just about coding, but it's about collaborative development and for this you need to document everything about your project.

**Comment by championshuttler** [comment]
I liked the last paragraph of you comment i will update the readme soon for sure :)

**Comment by emht** [comment]
Tell me about your project.  I will add the readme.md till you do.
